site_name: "scrapy_kit"
site_description: "scrapy kit"
repo_name: "spider-tool-kie/scrapy_kit"
watch: [mkdocs.yml, README.md, scrapy_kit]


theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/style.css
- css/material.css
- css/mkdocstrings.css
- css/insiders.css

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.details
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- literate-nav:
    nav_file: SUMMARY.md
    implicit_index: false
    tab_length: 2
- mkdocstrings:
    handlers:
      python:
        options:
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
- minify:
    minify_html: !ENV [DEPLOY, false]
