name: Python package
on:
  push:
    branches:
    - main
#     tags:
#       - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: pip install
        run: |
          pip install poetry
          poetry config virtualenvs.create false
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        run: |
          git config --global user.email "mtf201013@gmail.com"
          git config --global user.name "Pony Ma"
          poetry version patch
          version=$(poetry version | grep -Eo "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")
          git add .
          git commit -m "Bump version to v${version}"
          git tag v${version};
          git push --tags
      - name: Build and publish to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
